# ![](../img/b12_np.png)

<div style="page-break-after: always;"></div> 

#  넘파이(NumPy) 

<img src="https://www.tomasbeuzen.com/python-programming-for-data-science/_static/logo.png" alt="python for data science" width="300" height="300">


1. 넘파이 소개

2. 넘파이 배열

3. 배열 연산 및 전파

4. 인덱싱 및 슬라이싱

5. 넘파이 함수

<div style="page-break-after: always;"></div> 

<h2>학습 목표<span class="tocSkip"></span></h2>

- 넘파이 배열을 생성할 수 있다.  
  `np.array()` / `np.arange()` / `np.linspace()` / `np.full()` / `np.zeros()` /`np.ones()`
- 넘파이 배열 원소에 접근할 수 있다.  
  수치형 인덱싱/슬라이싱, 논리형 인덱싱, 환상적 인덱싱
- 배열에 대한 수학적 연산을 수행할 수 있다. 
- 연산 전파의 개념 및 활용 방법을 설명할 수 있다. 
- 배열을 재구성하여 배열의 모양을 변경할 수 있다.   
    `.reshape()` / `np.newaxis` / `.ravel()` / `.flatten()`
    - `np.속성`형태로 활용하는 속성
    - `배열이름.메소드()` 형태로 호출하는 메소드
- 넘파이 내장 함수를 활용할 수 있다.   
    `np.sum()`, `np.mean()`, `np.log()`, ...
    
<div style="page-break-after: always;"></div> 

## 1. 넘파이 소개

|![NumPy_logo_860 svg](https://user-images.githubusercontent.com/10287629/132848684-028e1b5e-bf8d-42b1-92e9-a7ca89aed7f3.png)<br>그림-1. 넘파이 로고<br>출처: [ko.wikipedia.org](https://ko.wikipedia.org/wiki/NumPy)|
|:---|

- 넘파이(NumPy)는 파이썬에서 "**수치 연산**을 위해 제공되는 근본적인 패키지"이다.
- 넘파이는 파이썬 표준 라이브러리로서 다음 분야에서 활용된다.
    - (벡터와 행렬 연산을 위한) 배열 처리
    - 선형대수학(linear algerba)
    - 기타 수치 연산
- 넘파이는 C 언어로 작성되었으며,  
  **넘파이 배열이** 파이썬 내장 리스트보다  
  (처리 속도와 메모리 효율 측면에서) **더 우수**하다.
- 추가적 공부 자료
    - [넘파이가 일반 파이썬보다 빠르다는 증명](https://www.datadiscuss.com/proof-that-numpy-is-much-faster-than-normal-python-array/)
    - [넘파이 배열의 메모리 효율성](https://www.jessicayung.com/numpy-arrays-memory-and-strides/)
    - [파이썬에서 넘파이로](https://www.labri.fr/perso/nrougier/from-python-to-numpy/)

- 넘파이를 설치하려면 아래와 같은 `conda` 명령을 써야 한다.
    - 아래 명령은 현재 활성화된 파이썬 가상환경에 넘파이를 설치한다.
    - 먼저 사용하려는 파이썬 가상환경을 활성화 상태로 만든 후에 넘파이를 설치해야 한다.
    - 이후로는 해당 가상환경을 활성화 한 상태에서 넘파이를 활용하면 된다.

```shell
$ conda install numpy  # 현재 활성화된 파이썬 가상환경에 넘파이를 설치    
```

- 넘파이 소개는 간단히 마치고, 넘파이 배열을 공부하자.

<div style="page-break-after: always;"></div> 

## 2. 넘파이 배열

### 2.1 배열의 개념

|![그림-2. 넘파이 배열의 다양한 모양](https://user-images.githubusercontent.com/10287629/126031429-34f6196a-3570-44a6-8824-8f53c21e2199.png)<br>그림-2. 넘파이 배열의 다양한 모양<br>출처: [Medium.com](https://medium.com/hackernoon/10-machine-learning-data-science-and-deep-learning-courses-for-programmers-7edc56078cde)|
|:---|

- 배열은 *n-차원(n-dimensional)* 자료구조이다.
    - 넘파이에서는 `ndarray` 자료형으로 표현한다.
    - 배열에는 (실수, 정수, 문자열 등과 같은) 모든 파이썬 기본 자료형 값을 저장할 수 있다.
    - (비 수치형 데이터보다는) *수치형 데이터를 저장하는 경우에 배열의 성능이 좋다*.
    - 일차원 배열은 열만으로 구성된다. 
    - 이차원 배열은 행과 열로 구성된다.
    - 삼차원 배열은 면, 행, 열로 구성된다.

- 넘파이 배열(ndarray)은 **동질적**(homogenous)인데,  
  배열 내부 원소의 자료형이 모두 같아야 한다는 의미이다.
- 그러므로 단일 넘파이 배열에  
  학생의 이름(문자열)과 점수(정수)를 함께 저장할 수는 없고,  
  이름 배열과 점수 배열로 분리해야 한다.
- 넘파이 배열은 넘파이가 제공하는 방대한 내장 함수와 호환성을 가진다.  
  넘파이 배열을 다양한 넘파이 내장 함수에서 사용할 수 있다는 의미이다.
- 넘파이 라이브러리 활용법을 관전해보자.  
  실습은 잠시 후부터 하기로 하고, 일단 관전해보자.  

- 넘파이 패키지를 수입한다. 

In [1]:
import numpy as np

- 1차원 배열부터 만들어 보자. 

In [2]:
arr_1d = np.array([7, 2, 9, 10])                # 넘파이 1차원 배열  
print(arr_1d)
print(type(arr_1d))
print(f"arr_1d 모양: {arr_1d.shape}")           # (4,): (4열) 벡터           <- (4,) !!!

[ 7  2  9 10]
<class 'numpy.ndarray'>
arr_1d 모양: (4,)


- 넘파이 1차원 배열과 파이썬 리스트는 출력 형태가 다르다. 

In [3]:
lst_1d = [7, 2, 9, 10]                          # 파이썬 1차원 리스트
print(lst_1d)
print(type(lst_1d))

[7, 2, 9, 10]
<class 'list'>


- 2차원 배열도 만들어 보자.  
  역시 넘파이 배열과 파이썬 리스트는 출력 형태가 다르다. 

In [4]:
arr_2d = np.array([[5.2, 3.0, 4.5],             # 넘파이 2차원 배열 생성
                   [9.1, 0.1, 0.3]])  
print(arr_2d)
print(type(arr_2d))
print(f"arr_2d 모양: {arr_2d.shape}")           # (2, 3): (2행 x 3열) 행렬

[[5.2 3.  4.5]
 [9.1 0.1 0.3]]
<class 'numpy.ndarray'>
arr_2d 모양: (2, 3)


In [5]:
lst_2d = [[5.2, 3.0, 4.5],                         # 파이썬 2차원 리스트 
          [9.1, 0.1, 0.3]]
print(lst_2d)
print(type(lst_2d))

[[5.2, 3.0, 4.5], [9.1, 0.1, 0.3]]
<class 'list'>


- 3차원 배열까지만 확인하자.  
  역시 넘파이 배열과 파이썬 리스트는 출력 형태가 다르다. 

In [6]:
arr_3d = np.array([[[1, 4, 7],                  # 넘파이 3차원 배열
                    [2, 9, 7], 
                    [1, 3, 0], 
                    [9, 6, 9]], 
                    
                   [[2, 3, 4], 
                    [-1, -1, 5], 
                    [-1, -1, 2], 
                    [-1, -1, 8]]])
print(arr_3d)
print(type(arr_3d))
print(f"arr_3d 모양: {arr_3d.shape}")           # (4, 3, 2): (4행 x 3열 x 2 면) 행렬

[[[ 1  4  7]
  [ 2  9  7]
  [ 1  3  0]
  [ 9  6  9]]

 [[ 2  3  4]
  [-1 -1  5]
  [-1 -1  2]
  [-1 -1  8]]]
<class 'numpy.ndarray'>
arr_3d 모양: (2, 4, 3)


In [7]:
lst_3d = [[[1, 4, 7],                  # 파이썬 3차원 리스트
           [2, 9, 7], 
           [1, 3, 0], 
           [9, 6, 9]], 

          [[2, 3, 4], 
           [-1, -1, 5], 
           [-1, -1, 2], 
           [-1, -1, 8]]]
print(lst_3d)
print(type(lst_3d))

[[[1, 4, 7], [2, 9, 7], [1, 3, 0], [9, 6, 9]], [[2, 3, 4], [-1, -1, 5], [-1, -1, 2], [-1, -1, 8]]]
<class 'list'>


- 모양이 (4,)인 1차원 배열의 모양을 변형할 수 있다. 
  - 모양이 (1, 4)인 2차원 배열로 변환
  - 모양이 (4, 1)인 2차원 배열로 변환

In [8]:
# arr_1d 벡터를 (1행 x 4열) 행렬로 변환하는 "무식한" 방법
arr_1d_row = np.array([arr_1d])                 # `[arr_1d]`라는 무식한 코드     
print(f"    arr_1d:  {arr_1d}")
print(f"arr_1d_row: {arr_1d_row}")
print(f"    arr_1d 모양: {arr_1d.shape}")       # (4,): (4열) 행렬
print(f"arr_1d_row 모양: {arr_1d_row.shape}")   # (1, 4): (1행 x 4열) 행렬

    arr_1d:  [ 7  2  9 10]
arr_1d_row: [[ 7  2  9 10]]
    arr_1d 모양: (4,)
arr_1d_row 모양: (1, 4)


In [9]:
# arr_1d 벡터를 (1행 x 4열) 행렬로 변환하는 "멋진" 방법 
arr_1d_row = arr_1d[np.newaxis, :]              # `arr_1d[np.newaxis, :]`라는 멋진 코드
print(f"    arr_1d 값: {arr_1d}")
print(f"arr_1d_row 값: {arr_1d_row}")
print(f"    arr_1d 모양: {arr_1d.shape}")       # (4,): (4열) 행렬
print(f"arr_1d_row 모양: {arr_1d_row.shape}")   # (1, 4): (1행 x 4열) 행렬

    arr_1d 값: [ 7  2  9 10]
arr_1d_row 값: [[ 7  2  9 10]]
    arr_1d 모양: (4,)
arr_1d_row 모양: (1, 4)


In [10]:
# arr_1d 벡터를 (4행 x 1열) 행렬로 변환하는 "무식한" 방법
arr_1d_col = np.array([[ 7],                   
                       [ 2], 
                       [ 9], 
                       [10]])                   #  (4행 x 1열) 행렬을 직접 지정한 코드
print(f"    arr_1d 값: \n{arr_1d}")
print(f"arr_1d_col 값: \n{arr_1d_col}")
print(f"    arr_1d 모양: {arr_1d.shape}")       # (4,): (4열) 행렬
print(f"arr_1d_col 모양: {arr_1d_col.shape}")   # (4, 1): (4행 x 1열) 행렬

    arr_1d 값: 
[ 7  2  9 10]
arr_1d_col 값: 
[[ 7]
 [ 2]
 [ 9]
 [10]]
    arr_1d 모양: (4,)
arr_1d_col 모양: (4, 1)


In [11]:
# arr_1d 벡터를 (4행 x 1열) 행렬로 변환하는 "멋진" 방법
arr_1d_col = arr_1d[:, np.newaxis]              # `arr_1d[:, np.newaxis]`라는 멋진 코드   
print(f"    arr_1d 값: \n{arr_1d}")
print(f"arr_1d_col 값: \n{arr_1d_col}")
print(f"    arr_1d 모양: {arr_1d.shape}")       # (4,): (4열) 행렬
print(f"arr_1d_col 모양: {arr_1d_col.shape}")   # (4, 1): (4행 x 1열) 행렬

    arr_1d 값: 
[ 7  2  9 10]
arr_1d_col 값: 
[[ 7]
 [ 2]
 [ 9]
 [10]]
    arr_1d 모양: (4,)
arr_1d_col 모양: (4, 1)


- 지금부터는 실습용 코드이다. 
  - 코딩은 (관전이 아니라) 실습으로 배워야 한다.
  - 코드를 보면서 똑 같이 입력하면 타자 연습이다. 
  - 일단 코드를 읽고 이해하라. 그리고 **보지 않고 작성해 보는 방식**으로 연습을 해야 한다. 
  - 코드를 생각해서 작성하려고 노력해야 한다.  
  - 오류를 해결하려는 노력이 중요하다. 
  - 오류 메시지를 복사해서 구글링해야 한다. 

- 넘파이 라이브러리 수입 작업부터 시작하자. 
  - 관례적으로 넘파이를 수입(import)할 때 별칭은 `np`로 지정한다.  
  - 넘파이를 사용할 때마다 'n-u-m-p-y'라고 입력하는  
    번거로움을 피하기 위해서 이렇게 별칭을 지정한다.

In [12]:
import numpy as np

- 넘파이 배열은 파이썬 리스트와 유사하다. 

In [13]:
my_list = [1, 2, 3, 4, 5]             # 파이썬 리스트
my_list

[1, 2, 3, 4, 5]

In [14]:
my_array = np.array([1, 2, 3, 4, 5])  # 넘파이 (일차원) 배열
print(my_array)       # print()를 써서 출력한 모습과 
my_array              # print()를 쓰지 않고 출력한 모습이 다름!

[1 2 3 4 5]


array([1, 2, 3, 4, 5])

- 넘파이 배열의 자료형을 확인하면, `ndarray`이다. 

In [15]:
type(my_array)  # 자료형 출력 함수

numpy.ndarray

- 파이썬 리스트와 달리,  
  넘파이 배열에는 **단일 자료형** 값(통상적으로 수치 값)만을 저장할 수 있다. 

In [16]:
# 파이썬 리스트에는 여러 자료형 값을 혼합해서 저장할 수 있다.
my_list = [1, "hi"]   
my_list

[1, 'hi']

In [17]:
# 넘파이 배열에 수치와 문자열이 혼합된 튜플을 저장하면 모두 문자열로 통일되어 저장된다.
my_array = np.array((1, "hi"))   
my_array                 

array(['1', 'hi'], dtype='<U11')

- 위에서 넘파이는 정수 `1`을 문자열 `'1'`로 자동적으로 강제적으로 변환하여 저장하였다.
- `U11`, `U32`, ... 등과 같은 `U#` 표현에서  
  `U`는 `Unicode` 자료형을 의미하며,  
  `#`은 자료형이 수용할 수 있는 원소의 개수를 의미한다.  
  
<div style="page-break-after: always;"></div> 

넘파이 배열의 개념을 공부했으니, 생성 방법을 실습하자.

<div style="page-break-after: always;"></div> 

### 2.2 배열의 생성

- ndarray를 생성하는 방법은 두 종류이다. 
    1. `np.array()` 함수에 (리스트 또는 튜플과 같이)  
       이미 존재하는 데이터를 매개변수로 전달하는 방법
    2. `np.arange()`, `np.linspace()`, `np.zeros()`, `np.ones()`, `np.full()` 등과 같은  
       넘파이 내장 함수를 이용하는 방법   

In [18]:
my_list = [1, 2, 3]  # 매개변수로 전달할 파이썬 리스트를 먼저 생성
np.array(my_list)    # np.array() 함수로 넘파이 배열 생성

array([1, 2, 3])

- 넘파이 다차원 배열을 생성할 수 있다.
    - 파이썬에서도, (리스트 내부에 리스트를 중첩하여) 다차원 리스트를 정의할 수 있다. 
    - 넘파이에서도, (대괄호 내부에 대괄호를 중첩하여) 다차원 배열을 정의할 수 있다.   

In [19]:
list_2d = [[1, 2], [3, 4], [5, 6]]  # 2차원 파이썬 리스트
list_2d

[[1, 2], [3, 4], [5, 6]]

In [20]:
array_2d = np.array(list_2d)        # 2차원 넘파이 배열
array_2d

array([[1, 2],
       [3, 4],
       [5, 6]])

- 3차원 배열부터는 꼼꼼해야 한다.

In [21]:
list_3d = [[[1, 2], 
            [3, 4]], 
           
           [[5, 6], 
            [7, 8]]]
list_3d

[[[1, 2], [3, 4]], [[5, 6], [7, 8]]]

In [22]:
array_3d = np.array(list_3d)
array_3d

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

- 지금까지는 `np.array()` 메소드로 넘파이 배열을 생성하는 방법을 공부했다. 
- 지금부터는 넘파이 배열을 생성하는 다른 방법을 공부해 보자. 

- 넘파이 `arange()`와 파이썬 `range()`는 비슷하지만 다르다. 
  - 파이썬 `range()`는 **수열**을 반환한다. 
  - 넘파이 `arnage()`는 (수열로 채워진) **배열**을 반환한다. 


In [23]:
np.arange(1, 5)    # 1부터 5(직전)까지, 1은 포함되지만 5는 제외한 배열 생성

array([1, 2, 3, 4])

In [24]:
range(1, 5)        # 파이썬 range()는 수열을 반환

range(1, 5)

In [25]:
list(range(1, 5))  # 파이썬 range()로 리스트 생성

[1, 2, 3, 4]

- 파이썬 `range()`와 비슷하게, `np.aragne()` 메소드에서도 **증분값**을 지정할 수 있다. 

In [26]:
np.arange(0, 11, 2)     # 0부터 11(직전)까지 증분은 2로 지정한 배열 생성

array([ 0,  2,  4,  6,  8, 10])

In [27]:
list(range(0, 11, 2))  # 파이썬 리스트

[0, 2, 4, 6, 8, 10]

- `np.linspace()`는 특정 구간을 균등한 간격으로 분할하는  
  벡터 공간(vector space), 다른 말로 **선형 공간**(linear space)을 배열로 생성한다. 
  - 구간은 **닫힌 구간**으로 처리되어, **마지막 값이 포함**된다. 

In [28]:
np.linspace(0, 10, 5)  # 0부터 10(포함)까지 4 등분하는 점에 대한 (4 구간) 배열 생성

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [29]:
np.linspace(0, 10)  # 개수의 기본값은 50

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

- 넘파이 `np.ones()`, `np.zeros()`, `np.full()` 메소드는 같은 값으로 채워진 배열을 반환한다.  

In [30]:
np.ones((2, 2))  # 모양이 (2행 x 2열)이고, 1로 채워진 배열 생성

array([[1., 1.],
       [1., 1.]])

In [31]:
np.zeros((3, 2))  # 모양이 (3행 x 2열)이고, 0으로 채워진 배열 생성

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [32]:
np.full((4, 3), 3.14)  # 모양이 (4행 x 3열)이고, 3.14로 채워진 배열 생성

array([[3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14]])

In [33]:
np.full((4, 3, 2), 3.14)  # 모양이 (4면 x 3행 x 2열)이고, 3.14로 채워진 배열 생성 

array([[[3.14, 3.14],
        [3.14, 3.14],
        [3.14, 3.14]],

       [[3.14, 3.14],
        [3.14, 3.14],
        [3.14, 3.14]],

       [[3.14, 3.14],
        [3.14, 3.14],
        [3.14, 3.14]],

       [[3.14, 3.14],
        [3.14, 3.14],
        [3.14, 3.14]]])

- 넘파이 배열에서 사용 가능한 속성 및 메소드가 매우 많다. 

In [34]:
dir(np.ndarray)       # 파이썬 dir() 함수로 np.ndarray 자료형에서 가용한 속성 및 메소드 조사

['T',
 '__abs__',
 '__add__',
 '__and__',
 '__array__',
 '__array_finalize__',
 '__array_function__',
 '__array_interface__',
 '__array_prepare__',
 '__array_priority__',
 '__array_struct__',
 '__array_ufunc__',
 '__array_wrap__',
 '__bool__',
 '__class__',
 '__complex__',
 '__contains__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__divmod__',
 '__doc__',
 '__eq__',
 '__float__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__ilshift__',
 '__imatmul__',
 '__imod__',
 '__imul__',
 '__index__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__irshift__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lshift__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__or__',
 '__pos__',
 '__pow__',
 '__radd__',
 '__rand__',
 '__rdivmod__',
 '__

- 넘파이는 다양한 난수 발생 함수를 제공하여, [통계적 무작위 추출](https://numpy.org/doc/1.16/reference/routines.random.html)을 지원한다.

In [35]:
# 모양이 (4행 x 2열)이고, 
# [0, 1) 구간의 균등 분포 난수로 채워진 배열 생성
# [0, 1) 구간은 0은 포함하지만, 1은 포함하지 않는다는 의미 

np.random.rand(4, 2)  

array([[0.23694622, 0.02485763],
       [0.60375286, 0.1533157 ],
       [0.14699935, 0.66036215],
       [0.45882427, 0.10273866]])

In [36]:
x = np.random.rand(4, 2)  # 모양이 (4행 x 2열)이고, [0, 1) 구간의 난수로 채워진 배열을 생성하여, 변수 x에 대입
x                         # np.random.rand() 메소드는 호출할 때마다 다른 난수를 반환

array([[0.19488549, 0.78836542],
       [0.35346797, 0.40655803],
       [0.57889359, 0.26140575],
       [0.51523074, 0.97761786]])

In [37]:
x.transpose()  # (행과 열을 전환한) 전치행렬을 반환하는 넘파이 메소드  

array([[0.19488549, 0.35346797, 0.57889359, 0.51523074],
       [0.78836542, 0.40655803, 0.26140575, 0.97761786]])

In [38]:
x.mean()  # 넘파이 배열 원소 전체의 평균

0.5095531059326994

In [39]:
x.astype(int)  # 넘파이 배열의 모든 원소 값을 정수로 (버림 처리하여) 변환

array([[0, 0],
       [0, 0],
       [0, 0],
       [0, 0]])

- 넘파이 배열의 생성 방법을 공부했고, 배열의 모양에 대해서 공부하자. 

<div style="page-break-after: always;"></div> 

### 2.3 배열의 모양

- 배열의 모양(shape)이란 배열의 차원 및 차원별 원소 개수에 의해서 결정된다. 
- 앞서 <그림-2>에서 보았듯이,  
  배열의 차원(dimension)에는 제한이 없으며,  
  모양과 크기를 원하는 대로 지정할 수 있다.
- 넘파이 배열이 가지는 중요한 속성 3 종을 소개한다. 
    - `.ndim`: 배열의 차원 개수
    - `.shape`: 각 차원에 대한 원소 개수 (각 차원에 대해서 `len()` 함수를 호출하는 것과 비슷함)
    - `.size`: 배열의 총 원소 개수 (모든 `.shape` 속성 값의 곱)

In [40]:
array_1d = np.ones(3)  # 1로 채워진 3열, 일차원 배열(즉, 벡터)이므로 인자를 단일(스칼라)값으로 지정하여 생성
print(f"  array_1d: {array_1d}")        
print(f"Dimensions: {array_1d.ndim}")   # 차원 개수
print(f"     Shape: {array_1d.shape}")  # 차원별 원소 개수가 (3)이 아닌 (3,) 즉 (3, None)으로 출력됨 (벡터인 경우)
print(f"      Size: {array_1d.size}")   # 전체 원소 개수

  array_1d: [1. 1. 1.]
Dimensions: 1
     Shape: (3,)
      Size: 3


- 배열에 대한 정보(차원 개수, 차원별 원소 개수, 총 원소 개수 및 원소 값)를  
  모두 출력하는 함수를 정의해 보자. 

In [41]:
def print_array(x):
    print(f"Dimensions: {x.ndim}")
    print(f"     Shape: {x.shape}")
    print(f"      Size: {x.size}")
    print("")
    print(x)

In [42]:
array_2d = np.ones((3, 2))  # 모두 1로 채운 (3 x 2) 모양인 이차원 배열이므로 인자를 (3, 2)라는 튜플로 지정
print_array(array_2d)

Dimensions: 2
     Shape: (3, 2)
      Size: 6

[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [43]:
array_4d = np.ones((2, 3, 4, 5))  # 모두 1로 채운 (2 x 3 x 4 x 5) 모양 배열이므로, 인자를 (2, 3, 4, 5)라는 튜플로 지정
print_array(array_4d)             # (3면 x 4행 x 5열) 모양 행렬이 2개

Dimensions: 4
     Shape: (2, 3, 4, 5)
      Size: 120

[[[[1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]]

  [[1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]]

  [[1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]]]


 [[[1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]]

  [[1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]]

  [[1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]]]]


- 3차원 이후부터, 배열 출력은 복잡해지기 시작한다.  
    - 대괄호(`[ ]`) 개수가 차원의 개수를 의미한다. 
    - 출력의 시작 부분에서 보이는 대괄호 4개 `[[[[`는 4차원 배열을 의미한다. 

- 넘파이 배열의 모양을 공부했고, 벡터의 개념을 공부하자. 

<div style="page-break-after: always;"></div> 

### 2.4 일차원 배열 및 벡터

- 넘파이에서 벡터의 모양은 3 종이다. 

In [44]:
x = np.ones(5)      # 원소가 모두 1인, 순수한 일차원 (행) 벡터
print_array(x)

Dimensions: 1
     Shape: (5,)
      Size: 5

[1. 1. 1. 1. 1.]


In [45]:
y = np.ones((1, 5))  # 원소가 모두 1이고 (1행, 5열) 모양인 이차원 배열, 행이 하나이므로 실질적으로 (행) 벡터
print_array(y)

Dimensions: 2
     Shape: (1, 5)
      Size: 5

[[1. 1. 1. 1. 1.]]


In [46]:
z = np.ones((5, 1))  # 원소가 모두 1이고 (5행, 1열) 모양인 이차원 배열, 열이 하나이므로 실질적으로 (열) 벡터 
print_array(z)

Dimensions: 2
     Shape: (5, 1)
      Size: 5

[[1.]
 [1.]
 [1.]
 [1.]
 [1.]]


- `np.array_equal()` 메소드로 두 배열의 모양과 원소 값이 모두 같은지를 판단할 수 있다. 

In [47]:
x      # (5, ) 배열, 5열로 구성된 행 벡터

array([1., 1., 1., 1., 1.])

In [48]:
y      # (1, 5) 배열

array([[1., 1., 1., 1., 1.]])

In [49]:
z      # (5, 1) 배열

array([[1.],
       [1.],
       [1.],
       [1.],
       [1.]])

In [50]:
np.array_equal(x, x)  # 모양과 모든 원소 값이 동등

True

In [51]:
np.array_equal(x, y)  # 모양(차원)이 다름, x는 일차원이고 y는 이차원 행 벡터

False

In [52]:
np.array_equal(x, z)  # 모양(차원)이 다름, x는 일차원이고 z는 이차원 열 벡터

False

In [53]:
np.array_equal(y, z) # 모양이 다름, 둘 다 이차원 배열이지만, y는 행 벡터이고 z는 열 벡터

False

- 배열 **모양의 차이**는 (수학적 연산 결과에서) 실질적으로 큰 차이를 만들어 낼 수 있다. 

In [54]:
x + y  # (1행, 5열)인 행 벡터의 (실질적) 모양이 유사하므로 가능한 연산

array([[2., 2., 2., 2., 2.]])

In [55]:
x + z  # (5열) 행 벡터와 (5행, 1열) 열 벡터의 덧셈은 (5행, 5열) 행렬로 '전파'됨 

array([[2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2.]])

In [56]:
y + z  # (1행, 5열) 행 벡터와 (5행, 1열) 열 벡터의 덧셈도 (5행, 5열) 행렬로 '전파'됨

array([[2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2.]])

- 이런 결과는 *전파(broadcasting)* 효과에 의한 결과이다.  
  다음 절에서 이에 대하여 공부하자.

<div style="page-break-after: always;"></div> 

## 3. 배열 연산 및 전파

### 3.1 반복 연산

- 넘파이 배열의 연산은  
  배열의 원소 수준에서 연산이 반복된다.   
  - 배열의 각 원소에 대해서 반복 연산 
  - 대응되는 원소 쌍에 대해서 반복 연산  


In [57]:
x = np.ones(4)  # 벡터 생성
x

array([1., 1., 1., 1.])

In [58]:
y = x + 1       # 벡터와 단일 값의 연산은, 벡터 원소 모두에 대하여 반복적으로 수행됨
y

array([2., 2., 2., 2.])

In [59]:
x - y           # 모양이 같은 벡터 간 연산은 대응되는 원소 쌍에 대하여 반복적으로 수행됨 

array([-1., -1., -1., -1.])

In [60]:
x == y          # 모양이 같은 벡터 간 연산은 대응되는 원소 쌍에 대하여 빈복적으로 수행됨 

array([False, False, False, False])

In [61]:
# x 및 y 벡터 값 확인
print(f"x = {x}\n")
print(f"y = {y}\n")

x = [1. 1. 1. 1.]

y = [2. 2. 2. 2.]



In [62]:
x * y                 # 모양이 같은 벡터 간 연산은 대응되는 원소 쌍에 대하여 빈복적으로 수행됨 

array([2., 2., 2., 2.])

In [63]:
x ** y                # 모양이 같은 벡터 간 연산은 대응되는 원소 쌍에 대하여 빈복적으로 수행됨 

array([1., 1., 1., 1.])

In [64]:
x / y                 # 모양이 같은 벡터 간 연산은 대응되는 원소 쌍에 대하여 빈복적으로 수행됨 

array([0.5, 0.5, 0.5, 0.5])

- 배열 연산이 원소 수준에서 반복되는 원리를 공부했고,  
  이제 연산의 전파라는 개념을 공부하자. 

<div style="page-break-after: always;"></div> 

### 3.2 연산 전파

- 모양이 다른 n차원 배열(ndarray) 간 연산에서  
  *연산 전파*가 불가능한 경우라면, 연산을 수행할 수 없다. 

In [65]:
a = np.ones((2, 2))  # 2행, 2열
b = np.ones((3, 3))  # 3행, 3열
print(a)
print()
print(b)
a + b                # ("전파"가 불가능한 경우이면) 모양이 다른 배열 간 연산에서 오류가 발생함 

[[1. 1.]
 [1. 1.]]

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


ValueError: operands could not be broadcast together with shapes (2,2) (3,3) 

- 연산의 `전파(broadcasting)`는  
  넘파이가 수치 연산을 수행하는 과정에서  
  모양이 다른 배열을 처리하는 방식이다.  
- 기본적으로 배열 간의 수치 연산은  
  배열 간에 대응되는 원소마다 반복적으로 수행된다. 
- 모양이 다른 배열 간에 연산 전파가 불가능한 경우에는 연산이 수행되지 않는다. 

- 파이 상점의 예제를 살펴보자. 
    - 파이 가격은 파이 종류마다 다르다. 
    - 파이 매출 수량은 파이 종류와 요일마다 집계되어 있다. 
    - 파이 종류와 요일에 따른 매출 금액을 계산하고 싶다.   

|![그림 3. 파이 상점의 가격과 판매 수량](https://user-images.githubusercontent.com/10287629/126039041-bc2f2ee8-10f4-410a-a562-88ce3a0e7971.png)<br>그림 3. 파이 상점의 가격과 판매 수량|
|:---|

In [66]:
cost = np.array([20, 15, 25])  # 파이 종류별 가격 벡터
cost

array([20, 15, 25])

In [67]:
sales = np.array([[2, 3, 1], [6, 3, 3], [5, 3, 5]])  # 요일별, 파이 종류별 판매 수량 행렬
sales

array([[2, 3, 1],
       [6, 3, 3],
       [5, 3, 5]])

- 가격 벡터와 판매 수량 행렬을 어떻게 곱할 수 있을까?

|![그림 4. 파이 매출액 계산 (반복) 논리](https://user-images.githubusercontent.com/10287629/126039432-02d14799-7d45-4ba4-a7cb-705d1bb7864c.png)<br>그림 4. 파이 매출액 계산 (반복) 논리|
|:---|


- 사실 `cost`는 <그림 4>와 달리 모양이 (3,)인 행 벡터이다. 

In [68]:
(cost.shape, sales.shape)

((3,), (3, 3))

In [69]:
cost

array([20, 15, 25])

In [70]:
sales

array([[2, 3, 1],
       [6, 3, 3],
       [5, 3, 5]])

In [71]:
total = np.zeros((3, 3))                  # 0으로 초기화 한 3행, 3열 행렬
total

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [72]:
for col in range(sales.shape[1]):         # sales.shape[1]은 열 크기 3
                                          # cost는 3열 벡터, sales[:, col]는 3행 벡터, 대응 원소마다 곱하기
    total[:, col] = sales[:, col] * cost  # sales 배열의 특정 열(원소 3개)과 cost 벡터(원소 3개)의 곱셈 연산
total

array([[ 40.,  60.,  20.],
       [ 90.,  45.,  45.],
       [125.,  75., 125.]])

- 위와 같은 방식이 마음에 들지 않는다면, 
    - (sales 행렬과 동일한 모양이 되도록) cost 벡터의 크기를 억지로 수정하여   
    - 대응되는 원소끼리 곱셈 연산이 수행되도록 할 수도 있다. 

|![그림 5. 파이 매출액 계산 (전파) 논리](https://user-images.githubusercontent.com/10287629/126039447-161c1630-b199-4c88-9dac-43148552dc2d.png)<br>그림 5. 파이 매출액 계산 (전파) 논리|
|:---|

- 여전히 <그림 5>와 달리, `cost`가 실제로는 모양이 (3,)인 행 벡터이다.

In [73]:
cost  # (3,) 

array([20, 15, 25])

- <그림 5>와 같은 모습의 열 벡터 `cost`로 재구성하자.

In [74]:
cost

array([20, 15, 25])

In [75]:
np.repeat(cost, 3)  # 원소마다(!) 3번씩 반복

array([20, 20, 20, 15, 15, 15, 25, 25, 25])

In [76]:
np.repeat(cost, 3).reshape((3, 3))  # 연속적으로 메소드를 호출하는 메소드 체이닝

array([[20, 20, 20],
       [15, 15, 15],
       [25, 25, 25]])

- 재구성된 `cost`로 행렬 간 곱셈을 수행하자. 

In [77]:
cost = np.repeat(cost, 3).reshape((3, 3))
cost

array([[20, 20, 20],
       [15, 15, 15],
       [25, 25, 25]])

In [78]:
sales

array([[2, 3, 1],
       [6, 3, 3],
       [5, 3, 5]])

In [79]:
cost * sales  # 여기서 cost와 sales 행렬은 모두 (3행, 3열)

array([[ 40,  60,  20],
       [ 90,  45,  45],
       [125,  75, 125]])

- 축하합니다!
    - 당신은 방금 (거의 수작업으로) 연산의 전파를 수행한 것입니다. 
    - 연산 `전파`란 넘파이가 `np.repeat()` 연산을  
      배후에서 자동적으로 수행하도록 만들어 주는 개념이다. 

- `전파`를 제대로 활용하여, 멋지게 처리하려면,  
  `cost`를 (3, 1) 배열로 재구성하여 `sales` 행렬에 곱하자.

In [80]:
cost = np.array([20, 15, 25]).reshape(3, 1)  # reshape() 메소드로 (3열) 행 벡터를 (3행, 1열) 열 벡터로 모양 변경
print(f" cost shape: {cost.shape}")
cost

 cost shape: (3, 1)


array([[20],
       [15],
       [25]])

In [81]:
sales = np.array([[2, 3, 1], [6, 3, 3], [5, 3, 5]])
print(f"sales shape: {sales.shape}")
sales

sales shape: (3, 3)


array([[2, 3, 1],
       [6, 3, 3],
       [5, 3, 5]])

In [82]:
sales * cost          # 두 배열 간의 전파를 활용한 연산 방식

array([[ 40,  60,  20],
       [ 90,  45,  45],
       [125,  75, 125]])

- 넘파이에서는,  
  크기가 작은 배열이  
  (크기가 큰 배열의 모양으로) 확장되는 방식으로  
  전파가 수행된다.  
  이렇게 해야 두 배열의 모양이 *연산 호환성*을 유지할 수 있게 된다. 

|![그림 6. 넘파이 배열 연산의 전파 개념](https://user-images.githubusercontent.com/10287629/126039928-f06efd55-e5b9-4dc0-b084-858e041dbc29.png)<br>그림 6. 넘파이 배열 연산의 전파 개념|
|:---|

- 넘파이 배열 연산에서는 전파 효과에 주의해야 한다. 
    - 크기가 작은 배열에 대하여  
      반복적으로 연산을 수행하는 방식보다는  
      전파 방식이 더 깔금하고 빠르게 처리된다. 
    - 전파 방식이 반복 연산 방식보다 더 빠르다는 것을 증명해 봅시다. 

In [83]:
cost = np.array([20, 15, 25]).reshape(3, 1)  # 열 벡터로 재구성 (파이 종류에 따라 행이 구분됨)
sales = np.array([[2, 3, 1],                 # 매출 행렬 (파이 종류에 따라 행이 구분됨)
                  [6, 3, 3],
                  [5, 3, 5]])
total = np.zeros((3, 3))

# 아래에서 np.squeeze() 메소드로 배열 축의 차원을 일차원으로 축소
# 아래에서 %timeit 명령은 주피터 노트북에서 제공하는 마법 명령으로, 아래에선 3번 반복 수행하여 가장 빠른 결과를 반환함
time_loop = %timeit -q -o -r 3 for col in range(sales.shape[1]): total[:, col] = sales[:, col] * np.squeeze(cost)
time_vect = %timeit -q -o -r 3 cost * sales
print(f"전파 방식이 반복 방식보다 {time_loop.average / time_vect.average:.2f}배 빨랐습니다.")

전파 방식이 반복 방식보다 9.51배 빨랐습니다.


- 파이썬 `timeit` 모듈에 대해서는 다음 문서를 참고하라. 
  - [파이썬 한글 공식 문서](https://docs.python.org/ko/3/library/timeit.html) 
  - [파이썬 영문 공식 문서](https://docs.python.org/3/library/timeit.html)
- 주피터 노트북과 같은 대화형 파이썬에서는 `%timeit`과 같은 [마법 명령](https://ipython.readthedocs.io/en/stable/interactive/magics.html#magic-timeit)을 쓸 수 있다. 

- (전파 방식을 쓰더라도) 모든 배열에 대해서 연산이 가능하지는 않다!
    - 넘파이는 연산 대상이 되는 두 배열에 대하여 다음과 같은 검사를 통하여  
      연산의 가능성(또는 호환성)을 판정한다.  
    - 뒤쪽 차원부터 시작해서, 앞쪽 차원으로 전진하면서 해당 차원의 크기를 비교한다.
    - 만일 다음 조건을 만족한다면 해당 차원의 호환성이 있다고 판정한다:
        - **해당 차원의 크기가 두 배열에서 모두 같다**, 또는
        - **해당 차원의 크기가 두 배열 중 어느 하나에서 1이다**   
- 아래 코드를 활용해서 연산 가능성 및 호환성을 판정하는 논리를 이해하자. 

In [84]:
def try_add(a, b):
    print(f"a: \n{a}")
    print(f"b: \n{b}")

    print(f"배열 a의 모양: {a.shape}")
    print(f"배열 b의 모양: {b.shape}")

    try:
        print(f"a + b: \n{a + b}")
        print(f"배열 (a + b)의 모양: {(a + b).shape}")
    except:
        print(f"오류: 배열의 모양이 전파 호환성을 만족하지 않는다!")    

In [85]:
# 완전히 동일한 모양의 두 배열은 호환성이 있다. 
a = np.ones((3, 2))
b = np.ones((3, 2))

try_add(a, b)

a: 
[[1. 1.]
 [1. 1.]
 [1. 1.]]
b: 
[[1. 1.]
 [1. 1.]
 [1. 1.]]
배열 a의 모양: (3, 2)
배열 b의 모양: (3, 2)
a + b: 
[[2. 2.]
 [2. 2.]
 [2. 2.]]
배열 (a + b)의 모양: (3, 2)


In [86]:
# 뒤쪽 차원에서 둘 중의 하나가 1인 경우이므로 호환성이 있다.
a = np.ones((3, 1))
b = np.ones((3, 2))

try_add(a, b)

a: 
[[1.]
 [1.]
 [1.]]
b: 
[[1. 1.]
 [1. 1.]
 [1. 1.]]
배열 a의 모양: (3, 1)
배열 b의 모양: (3, 2)
a + b: 
[[2. 2.]
 [2. 2.]
 [2. 2.]]
배열 (a + b)의 모양: (3, 2)


In [87]:
# 뒤쪽 차원은 크기가 같고, 앞쪽 차원에서 둘 중의 하나가 1인 경우이므로 호환성이 있다.  
a = np.ones((1, 3))
b = np.ones((3, 3))

try_add(a, b)

a: 
[[1. 1. 1.]]
b: 
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
배열 a의 모양: (1, 3)
배열 b의 모양: (3, 3)
a + b: 
[[2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]]
배열 (a + b)의 모양: (3, 3)


In [88]:
# 뒤쪽 차원 크기는 같지만, 앞쪽 차원 크기가 다르고, 둘 중의 하나가 1이 아니면 호환성이 없다. 
a = np.ones((2, 3))
b = np.ones((3, 3))

try_add(a, b)

a: 
[[1. 1. 1.]
 [1. 1. 1.]]
b: 
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
배열 a의 모양: (2, 3)
배열 b의 모양: (3, 3)
오류: 배열의 모양이 전파 호환성을 만족하지 않는다!


In [89]:
# 뒤쪽 차원은 크기가 같고, 앞쪽 차원에서 둘 중의 하나가 1인 경우이므로 호환성이 있다.  
a = np.ones((1, 2, 3))
b = np.ones((3, 2, 3))

try_add(a, b)

a: 
[[[1. 1. 1.]
  [1. 1. 1.]]]
b: 
[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]
배열 a의 모양: (1, 2, 3)
배열 b의 모양: (3, 2, 3)
a + b: 
[[[2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]]]
배열 (a + b)의 모양: (3, 2, 3)


In [90]:
#뒤쪽 차원 크기는 같지만, 앞쪽 차원 크기가 다르고, 둘 중의 하나가 1인 경우도 아니므로 호환성이 없다.   
a = np.ones((2, 2, 3))
b = np.ones((3, 2, 3))

try_add(a, b)

a: 
[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]
b: 
[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]
배열 a의 모양: (2, 2, 3)
배열 b의 모양: (3, 2, 3)
오류: 배열의 모양이 전파 호환성을 만족하지 않는다!


- 전파의 개념을 공부했으니, 이제 배열 재구성을 공부하자. 

<div style="page-break-after: always;"></div> 

### 3.3 배열 재구성

- 넘파이 배열의 (모양을 변경하는) 재구성(reshaping) 방법에서 중요한 3 종을 공부하자. 
    - `.rehshape()`
    - `np.newaxis`
    - `.ravel()` / `.flatten()`

- `.reshape()` 메소드는 상당히 직관적이다. 

In [91]:
x = np.full((4, 3), 3.14)  # (4, 3) 차원을 12개의 3.14 값으로 채운 배열 
x

array([[3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14]])

In [92]:
x.reshape(6, 2)           # (6, 2) 차원으로 재구성

array([[3.14, 3.14],
       [3.14, 3.14],
       [3.14, 3.14],
       [3.14, 3.14],
       [3.14, 3.14],
       [3.14, 3.14]])

In [93]:
x.reshape(2, -1)  # -1 값을 지정하면, 적절한 차원 크기를 자동으로 계산하여 처리 (가능하다면)

array([[3.14, 3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14, 3.14]])

In [94]:
y = np.array([ [1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12] ])  # (6, 2) 배열
y

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [95]:
y.reshape(2, 6)  # (2, 6) 모양으로 재구성

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [96]:
y.reshape(-1, 4)  # (3, 4) 모양으로 자동 처리됨

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [97]:
y  # y는 원본 불변!

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

- 아래에서 (3,) 벡터 a와 (3, 2) 행렬 b의 덧셈은 불가능하다. 
- `np.newaxis`를 활용하여 이 문제를 해결하는 방법을 알아보자.

In [98]:
a = np.ones(3)       # 3열 벡터 
print_array(a)    
b = np.ones((3, 2))  # (3, 2) 모양 행렬
print_array(b)

Dimensions: 1
     Shape: (3,)
      Size: 3

[1. 1. 1.]
Dimensions: 2
     Shape: (3, 2)
      Size: 6

[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [99]:
a + b

ValueError: operands could not be broadcast together with shapes (3,) (3,2) 

- 때때로 배열에 차원을 추가하고 싶을 때가 있다. 
    - 연산 호환성 문제를 해결하기 위해서, 배열에 차원을 추가하는 경우가 있다. 
    - 전파 효과를 의도적으로 만들어 내기 위한 조치이다.
    - `np.newaxis`을 사용하여 이러한 작업을 수행할 수 있다. 
    - `np.newaxis`는 '새로운 축'이라는 의미이다. 
    - 사실 `np.newaxis`는 `None`과 동등한 값이다. 
    - 위 코드에서 오류가 발생했던 `a + b` 명령의 호환성 문제를 해결하기 위해서  
    `a`의 차원을 추가해보자.  

In [100]:
np.newaxis == None  # `np.newaxis`과 `None`의 값 동등성 확인

True

In [101]:
np.newaxis is None  # `np.newaxis`과 `None`의 (값 동등성이 아닌) 객체 동일성 확인

True

In [102]:
a  # (3,) 행 벡터

array([1., 1., 1.])

In [103]:
# `a[:, np.newaxis]` 코드를 써서 행 벡터를 (3, 1) 행렬로 변환하고 차원과 모양을 검토
print_array(a[:, np.newaxis])  # `a[:, None]`라고 써도 동등한 효과, 행만 있고, 열은 없는 행렬로 변환

Dimensions: 2
     Shape: (3, 1)
      Size: 3

[[1.]
 [1.]
 [1.]]


In [104]:
b

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [105]:
# 행 벡터 a에 차원을 추가하여 (3, 1) 행렬로 변환하고 덧셈 연산 시도 
a[:, np.newaxis] + b  

array([[2., 2.],
       [2., 2.],
       [2., 2.]])

- `np.newaxis`로 배열의 차원을 강제로 늘리는 작업을 `.reshape()`로도 동등하게 수행할 수 있다.  

In [106]:
np.arange(1, 5)

array([1, 2, 3, 4])

In [107]:
v4 = np.arange(1, 5)  # 4열 벡터
print_array(v4)

Dimensions: 1
     Shape: (4,)
      Size: 4

[1 2 3 4]


In [108]:
v4  # v4 모습을 .newaxis 및 .reshape()로 변경해보자. 

array([1, 2, 3, 4])

In [109]:
m41_by_newaxis = v4[:, np.newaxis]  # np.newaxis를 써서 (4, 1) 행렬로 변환, 열이 None인 행렬
print_array(m41_by_newaxis) 

Dimensions: 2
     Shape: (4, 1)
      Size: 4

[[1]
 [2]
 [3]
 [4]]


In [110]:
m41_by_reshape = v4.reshape(4, 1)  # .reshape()를 써서 (4, 1) 행렬로 변환
print_array(m41_by_reshape)

Dimensions: 2
     Shape: (4, 1)
      Size: 4

[[1]
 [2]
 [3]
 [4]]


In [111]:
v4  # v4의 차원을 (1, 4) 모양으로 .newaxis와 .reshape()로 변경해보자. 

array([1, 2, 3, 4])

In [112]:
m14_by_newaxis = v4[np.newaxis, :]  # np.newaxis를 써서 1행 4열 행렬로 변환, 행이 None
print_array(m14_by_newaxis) 

Dimensions: 2
     Shape: (1, 4)
      Size: 4

[[1 2 3 4]]


In [113]:
m14_by_reshape = v4.reshape(1, 4)  # .reshape()를 써서 1행 4열 행렬로 변환
print_array(m14_by_reshape)

Dimensions: 2
     Shape: (1, 4)
      Size: 4

[[1 2 3 4]]


- `.ravel()` 및 `.flatten()` 메소드로 다차원 배열을 일차원으로 *평면화* 할 수 있다. 
    - `.flatten()` 메소드의 이름공간은 `numpy.ndarray.flatten`이고, **복사본(copy)**을 반환한다. 
    - `.ravel()` 메소드의 이름공간은 `numpy.ravel`이고, **뷰(view)**를 반환한다.
    - 두 메소드의 실행 결과는 동일하게 보이는데,  
      공통적으로 평면화된 일차원 배열에 대한 참조를 반환한다. 

In [114]:
print_array(x)  # 3.14로 모두 채운 (4, 3) 모양의 행렬

Dimensions: 2
     Shape: (4, 3)
      Size: 12

[[3.14 3.14 3.14]
 [3.14 3.14 3.14]
 [3.14 3.14 3.14]
 [3.14 3.14 3.14]]


In [115]:
print_array(x.flatten())  # (4, 3) 모양을 (12,) 모양으로 평면화한 복사본

Dimensions: 1
     Shape: (12,)
      Size: 12

[3.14 3.14 3.14 3.14 3.14 3.14 3.14 3.14 3.14 3.14 3.14 3.14]


In [116]:
print_array(x.ravel())  # (4, 3) 모양을 (12,) 모양으로 평면화한 뷰

Dimensions: 1
     Shape: (12,)
      Size: 12

[3.14 3.14 3.14 3.14 3.14 3.14 3.14 3.14 3.14 3.14 3.14 3.14]


 - `.flatten()` 메소드와 `.ravel()` 메소드의 실행 결과는 동일한 것처럼 보인다.
 - 하지만 두 메소드의 실행 과정은 미묘하게 다르다.  
    - `a.flatten()`의 `base` 값은 `None`인데,  
      이는 메소드가 반환하는 값이 복사본(copy)라는 의미이다. 
    - `a.ravel()`의 `base` 값은 원본 배열인데,  
      이는 메소드가 반환하는 값이 뷰(view)라는 의미이다.

- 복사본을 사용하는 `a.flatten()`과 <br>
  뷰를 통해 원본을 참조하는 `a.ravel()`의 <br>
  차이로 인하여 다음과 같은 점에서 주의가 필요하다. 
    - 복사본을 사용하는 방식은 원본을 참조하는 방식에 비하여 훨씬 느리다.  
      메모리 상에서 복사본을 생성하는 시간이 소요되기 때문이다.
    - 복사본을 사용하는 방식이 원본에 대한 오류 값의 파급 효과를 차단하기 때문에  
      오류 방지 혹은 오류 지역화 차원에서 유리할 수 있다.      

In [117]:
a = np.array([[1,2],[3,4]])

f = a.flatten()                   # 복사본 np.ndarray.flatten(a)
r = a.ravel()                     # 뷰 np.ravel(a)

print(a)
print(f"    f: {f}")              # a.flatten()의 반환값 확인 (두 메소드의 반환값은 동일함)
print(f"    r: {r}")              # a.ravel()의 반환값 확인   (두 메소드의 반환값은 동일함) 

print(f"id(a): {id(a)}")          # a의 고유값 확인 (a, r, f)의 메모리 주소가 모두 상이함
print(f"id(f): {id(f)}")          # f의 고유값 확인 (a, r, f)의 메모리 주소가 모두 상이함
print(f"id(r): {id(r)}")          # r의 고유값 확인 (a, r, f)의 메모리 주소가 모두 상이함

print(f"\nbase of f:\n{f.base}")  # a.flatten()의 base는 None                     (a.flatten()의 반환값이 복사본이라는 의미)
print(f"\nbase of r:\n{r.base}")  # a.ravel()의 base는 해당 작업에 대한 원본 배열 (a.ravel()의   반환값이 뷰라는 의미)


[[1 2]
 [3 4]]
    f: [1 2 3 4]
    r: [1 2 3 4]
id(a): 2011579253456
id(f): 2011579253552
id(r): 2011579253648

base of f:
None

base of r:
[[1 2]
 [3 4]]


- 배열 재구성을 실습했고, 이제 인덱싱/슬라이싱 실습을 진행하자. 

<div style="page-break-after: always;"></div> 

## 4. 인덱싱 및 슬라이싱

- 인덱싱(indexing)이란 배열의 특정 원소에 (인덱스 값을 통하여) 접근하는 것을 의미한다.  
  - 리스트 인덱싱과 배열 인덱싱은 비슷한 원리이다. 
  - 리스트는 근본적으로 일차원이지만, 배열은 근본적으로 다차원이라는 점에서  
    배열에서는 올바르게 인덱싱하기 위해서 리스트에서보다 더 주의해야 한다.  
- 수치형 인덱싱과 논리형 인덱싱이 모두 가능하다. 

### 4.1 수치형 인덱싱

- 인덱싱을 위한 인덱스는 0부터 시작한다. 
- 슬라이싱은 인덱스 값의 범위를 `start:end` 형식으로 지정하는데,    
  시작 값 `start`는 포함되지만, 종료 값 `end`는 슬라이싱 대상에서 제외된다. 

In [118]:
x = np.arange(10)  # 넘파이 배열 생성
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [119]:
x[3]  # 넘파이 배열에서 3번 원소에 접근

3

In [120]:
x[2:]  # 시작 값 2번 이후의 모든 원소에 접근

array([2, 3, 4, 5, 6, 7, 8, 9])

In [121]:
x[:4]  # 종료 값 4번까지의 모든 원소에 접근

array([0, 1, 2, 3])

In [122]:
x[2:5]  # 시작 값 2번에서 종료 값 5번(을 제외한 범위)까지의 원소에 접근

array([2, 3, 4])

In [123]:
x[2:3]  # 시작 값 2번에서 종료 값 3번(을 제외한 범위)까지의 원소에 접근

array([2])

In [124]:
x[-1]  # `-1` 인덱스 값으로 마지막 원소에 접근이 가능함

9

In [125]:
x[-2] # `-2` 인덱스 값으로 마지막 원소의 직전 원소에 접근 

8

In [126]:
x[5:0:-1]  # 시작 값을 5로, 종료 값을 0으로, 증분 값을 -1로 지정하여 인덱싱 (종료 값은 제외)

array([5, 4, 3, 2, 1])

- 증분을 음수로 지정해도, 종료값 직전까지 처리된다는 점에 유의하라. 

- 이차원 배열에 대한 인덱싱

In [127]:
x = np.random.randint(10, size=(4, 6))  # randint() 함수로 크기가 (4, 6)인 배열을 난수로 채움
x                                       # [0, 10) 범위에서 무작위 정수 추출

array([[9, 4, 6, 1, 2, 0],
       [4, 5, 4, 6, 3, 8],
       [9, 0, 5, 1, 4, 1],
       [7, 5, 0, 4, 3, 2]])

- `randint(low, high=None, size=None, dtype='l')` 
    - 정수형 난수를 `[low, high)` 범위에서 발생시킨다.  
      범위에서 low는 포함되고, high는 제외된다. 
    - 추출된 정수형 난수는 균등분포를 이룬다.
    - `high` 값을 생략하면 `[0, low)` 범위가 적용되어,  
      0이 `low`로, `low`가 `high`로 처리된다. 
    - `size`로 지정한 모양의 배열을 구성하여 반환한다.  
      생략하면 단일 정수형 난수를 반환한다.   

In [128]:
x[3, 1]  # 3행 1열 원소에 접근

5

In [129]:
x[3][1]  # 이런 표현도 가능함

5

In [130]:
x[3]  # 3 행 전체에 접근

array([7, 5, 0, 4, 3, 2])

In [131]:
x.shape  # 배열의 모양

(4, 6)

In [132]:
len(x)  # 배열의 길이는 첫 차원의 원소 개수 (이차원 배열이면 행 개수)

4

In [133]:
x

array([[9, 4, 6, 1, 2, 0],
       [4, 5, 4, 6, 3, 8],
       [9, 0, 5, 1, 4, 1],
       [7, 5, 0, 4, 3, 2]])

In [134]:
x[:, 2]  # 행은 전체, 열은 2열만, 반환되는 결과가 열 벡터 모양답지는 않음!

array([6, 4, 5, 0])

In [135]:
x[2:, :3]  # 2행 이후의 행, 그리고 3열까지의 열

array([[9, 0, 5],
       [7, 5, 0]])

- 전치 행렬(transposed matrix)이란 행과 열을 뒤바꾼(전치) 행렬을 의미한다. 
  - 기존 행렬의 행이 전치 행렬의 열로,  
    기존 행렬의 열이 전치 행렬의 행으로 전치된다. 
  - 예를 들어서 모양이 (4, 6)인 행렬이 있을 때,  
    전치 행렬의 모양은 (6, 4)가 된다. 

In [136]:
x.T  # 전치행렬(transposed matrix)

array([[9, 4, 9, 7],
       [4, 5, 0, 5],
       [6, 4, 5, 0],
       [1, 6, 1, 4],
       [2, 3, 4, 3],
       [0, 8, 1, 2]])

In [137]:
x   # 원래 모습과 전치행렬의 모습을 비교하자. 

array([[9, 4, 6, 1, 2, 0],
       [4, 5, 4, 6, 3, 8],
       [9, 0, 5, 1, 4, 1],
       [7, 5, 0, 4, 3, 2]])

- 인덱싱을 통하여 배열 원소의 값을 변경할 수 있다. 

In [138]:
z = np.zeros(5)   # 0으로 채운 (5,) 벡터 생성
z

array([0., 0., 0., 0., 0.])

In [139]:
z[0] = 5  # 인덱싱을 통한 원소 값 대입
z

array([5., 0., 0., 0., 0.])

In [140]:
x[1, 1] = 555555  # 인덱싱을 통한 원소 값 대입
x

array([[     9,      4,      6,      1,      2,      0],
       [     4, 555555,      4,      6,      3,      8],
       [     9,      0,      5,      1,      4,      1],
       [     7,      5,      0,      4,      3,      2]])

- 수치형 인덱싱을 실습했고, 이제 논리형 인덱싱 실습을 진행하자. 

<div style="page-break-after: always;"></div> 

### 4.2 논리형 인덱싱

In [141]:
x = np.random.rand(10)  # 10개 난수로 일차원 배열 생성
x

array([0.50566713, 0.54940566, 0.75712053, 0.28960692, 0.89029392,
       0.21434927, 0.50735978, 0.87021902, 0.85824074, 0.33265847])

In [142]:
x + 1  # 모든 원소를 1만큼 증가시킨 복사본 반환 (원본은 불변)

array([1.50566713, 1.54940566, 1.75712053, 1.28960692, 1.89029392,
       1.21434927, 1.50735978, 1.87021902, 1.85824074, 1.33265847])

In [143]:
x_thresh = x > 0.5  # 10개 원소 모두에 대해서 비교 연산을 수행한 결과를 배열로 반환받아서 x_thresh에 저장
x_thresh

array([ True,  True,  True, False,  True, False,  True,  True,  True,
       False])

In [144]:
x[x_thresh] = 0.5  # (배열 원소 값이 0.5보다 크다는) 조건을 만족하는 모든 원소 값에 0.5를 대입
x

array([0.5       , 0.5       , 0.5       , 0.28960692, 0.5       ,
       0.21434927, 0.5       , 0.5       , 0.5       , 0.33265847])

In [145]:
x = np.random.rand(10)  # 다시 난수로 초기화
x

array([0.10502591, 0.77188488, 0.44679155, 0.1049922 , 0.35466291,
       0.79043999, 0.10373626, 0.73856455, 0.46776495, 0.19906446])

In [146]:
x[x > 0.5] = 0.5  # 동일한 작업을 재 수행
x

array([0.10502591, 0.5       , 0.44679155, 0.1049922 , 0.35466291,
       0.5       , 0.10373626, 0.5       , 0.46776495, 0.19906446])

- 수치형과 논리형 인덱싱을 실습했고, 이제 환상적 인덱싱을 공부하자. 

<div style="page-break-after: always;"></div> 

### 4.3 환상적 인덱싱

- 넘파이 배열에 대한 "환상적" 인덱싱(fancy indexing)도 가능하다. 


In [147]:
x = np.arange(0, 100, 10)
x

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

- 아래 표현의 결과를 비교하여 보자: 
  - 리스트에 배열 원소를 직접 대입한 표현
  - 인덱스 리스트를 만들고, 이를 통하여 배열을 환상적으로 인덱싱하는 표현

In [148]:
[x[3], x[7], x[0]]  # 리트스에 배열 원소를 직접 지정한 표현

[30, 70, 0]

In [149]:
ndx = [3, 7, 0]     # 인덱스 리스트
x[ndx]              # 인덱스 리스트로 배열 인덱싱

array([30, 70,  0])

In [150]:
x[[3, 7, 0]]        # x[ndx]와 같은 표현 

array([30, 70,  0])

- 리스트에 배열 원소를 직접 지정한 `[x[3], x[7], x[0]]` 표현과  
  인덱스 리스트로 배열을 인덱싱한 `x[[3, 7, 0]]` 표현은 동일한 결과를 산출한다.  

- 인덱스 배열을 넘파이 다차원 배열로 구성하면,  
  넘파이 배열에 대한 인덱싱을 통하여  
  다차원 배열처럼 환상적으로 인덱싱이 가능하다.  

In [151]:
ndx = np.array([[3, 7],   # 인덱스 배열을 다차원으로 정의
                [0, 1]])
x[ndx]                    # 인덱스 배열의 모습대로 배열 인덱싱 

array([[30, 70],
       [ 0, 10]])

- 환상적 인덱싱으로 다차원 배열의 특정 원소에 접근할 수 있고,  
  이를 일차원 배열처럼 구성할 수 있다. 

In [152]:
x = np.arange(12).reshape((3, 4))  # 3차원 배열 생성
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [153]:
row = np.array([0, 1, 2])         # 행 인덱스 배열
col = np.array([2, 1, 3])         # 열 인덱스 배열
x[row, col]                       # [X[0, 2], X[1, 1], X[2, 3]]

array([ 2,  5, 11])

- 위 코드는 행과 열에 대한 인덱스 배열을 만들고,  
  이를 통하여 2차원 배열의 특정 원소에 접근한 결과이다.  
  - 행 인덱스와 열 인덱스에서 대응되는 인덱스 쌍을 가져와서 원 배열에 접근한다.  
  - 결과적으로 일차원 배열이 생성되었다. 

- 환상적 인덱싱으로 2차원 배열을 인덱싱하고 생성할 수 있다:

In [154]:
x[row[:, np.newaxis], col]

array([[ 2,  1,  3],
       [ 6,  5,  7],
       [10,  9, 11]])

- 위 코드에서  
  - 행은 `row[:, np.newaxis]`으로 지정되었다.    
  - 열은 `col`로 지정되었다. 
  - 결과적으로 2차원 배열이 생성되었다. 

- 환상적 인덱싱과 기존 인덱싱 기법을 혼합 적용하는 결합형 인덱싱이 가능하다. 

In [155]:
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

- 환상적 인덱싱과 단순 인덱싱을 결합한 예제이다: 

In [156]:
x[2, [2, 0, 1]]  # 2행, [2, 0, 1]열을 인덱싱

array([10,  8,  9])

- 환상적 인덱싱과 슬라이싱을 결합한 예제이다: 

In [157]:
x[1:, [2, 0, 1]]

array([[ 6,  4,  5],
       [10,  8,  9]])

- 환상적 인덱싱과 논리형 인덱싱을 결합한 예제이다: 

In [158]:
mask_col = np.array([1, 0, 1, 0], dtype=bool)  # 열에 적용할 논리형 마스크
x[row[:, np.newaxis], mask_col]                # 모든 행, mask_col 열

array([[ 0,  2],
       [ 4,  6],
       [ 8, 10]])

수치형/논리형 인덱싱과 환상적 인덱싱까지 공부했고, 이제 넘파이 함수를 공부하자

<div style="page-break-after: always;"></div> 

## 5. 넘파이 함수

### 5.1 넘파이 함수 활용

- 넘파이는 수학적 연산을 처리하는 (방대한 규모의) 내장 함수를 제공한다.  
    - 넘파이 내장 함수를 써서 거의 모든 종류의 수학적 연산이 가능하다. 
    - 두 변의 길이가 각각 3m와 4m인 직각 삼각형의 빗변 길이를 구하는 예제를 살펴보자. 

|![그림 7. 직각삼각형 빗변 길이 구하기](https://user-images.githubusercontent.com/10287629/126061821-fc14f3d0-f0e9-4575-a8b1-26f663ca3d07.png)<br>그림 7. 직각삼각형 빗변 길이 구하기|
|:---|

In [159]:
sides = np.array([3, 4])  # 직각삼각형의 두 변 길이

- 다음과 같은 피타고라스 정리에 의해서 이 문제를 해결해보자. 

![](../img/chapter5/pythagoras.png)

In [160]:
np.sqrt(np.sum([
    np.power(sides[0], 2), 
    np.power(sides[1], 2)   
]))                        # 피타고라스 공식을 적용한 (넘파이 배열답지 않은) 코드

5.0

- 넘파이 배열을 활용한다는 취지에서, 벡터화된 연산을 적용한 새로운 코드는 다음과 같다.  

In [161]:
(sides ** 2).sum() ** 0.5  # 배열 원소 각각을 제곱하여, 합을 구하고, 이 결과값의 0.5 제곱을 구함

5.0

- 넘파이 내장 함수에서 제공하는 기능을 직접 적용한 코드는 다음과 같다. 

In [162]:
np.linalg.norm(sides)  # linalg(linear algebra, 선형대수학)에서 제공하는 norm() 메소드

5.0

- `norm()`에서 뜻하는 놈(norm)에 대해서 [이곳](https://bskyvision.com/825)을 참고하면,  
  우리가 적용한 메소드가 "*L<sub>2</sub> norm*" 또는 "*유클리드 놈*"에 해당한다는 것을 알 수 있다. 

- `np.hypot()`는 직각삼각형의 빗변 길이를 구하는 넘파이 메소드이다.   

In [163]:
np.hypot(*sides)  # 넘파이가 제공하는 직각삼각형의 빗변 길이를 구하는 메소드

5.0

- 직전 코드에서 매개변수 이름 `sides` 앞에 `*`를 붙인 형태에 주목하자. 
    - `*`는 몇 개가 될지 모르는 다수 데이터를 매개변수로 전달하고 싶을 때 사용하는 지시어이다. 
    - 개수가 확정되지 않은 다수 데이터를 리스트 등으로 한꺼번에 전달하고,  
      이를 단일 매개변수로 받는 방법이다.
    - 매개변수에 등장하는 `*sides`라는 표현에서,  
      `*`를 *해체(unpack) 지시어*라고 부르는데,  
      `sides`처럼 (리스트 또는 튜플로)  
      *통합(pack)된 집합체의 원소를 개별적으로 해체(unpack)*하라는 표시이다.   
    - 다음 예제 코드를 참고하라. 

In [164]:
def names(*args):
    for name in args[:-1]:             # 마지막 원소 직전까지 반복
        print(f"{name}", end=",  ")    # end 인자로 쉼표만 찍고, 줄바꿈을 방지
    print(f"{args[-1]}")               # 반복을 종료하면, 마지막 원소를 출력하고 줄바꿈 처리

          
names("고선지", "강감찬", "이순신")
names("황진이", "성춘향")
names("도깨비")

고선지,  강감찬,  이순신
황진이,  성춘향
도깨비


- 파이썬에서 `**kwargs`라는 매개변수를 쓸 수도 있다. 
  - 함수에 `key=value` 형태로 매개변수를 불특정 다수로 전달할 때 사용한다.
  - 아래 코드를 보라.

In [165]:
def keyed_name(**kwargs):  # 함수 정의
    for key, value in kwargs.items():
        print(f"{value}님은 {key}입니다.")
    print()

keyed_name(여성='황진이')
keyed_name(남성='서화담', 여성='황진이')
keyed_name(남성='서화담', 여성='황진이', 학생='나학생', 회사원='김사원')

황진이님은 여성입니다.

서화담님은 남성입니다.
황진이님은 여성입니다.

서화담님은 남성입니다.
황진이님은 여성입니다.
나학생님은 학생입니다.
김사원님은 회사원입니다.



- 넘파이 함수를 공부했다. 이제 벡터화 개념을 공부하자.

<div style="page-break-after: always;">

### 5.2 벡터화

- 넓은 의미에서, *벡터화(vectorizing)*는 <br>
  연산 수행 과정에서 최적화된 C 코드를 활용하는 것에 대한 통칭이다. 
- 짧게 설명하자면,  
  넘파이 배열은 (동일한 자료형만을 저장할 수 있는) 단일형 집합체이므로,  
  연산을 수행하기 전에, 연산의 수행 가능성을 사전 점검할 필요가 없다.  
  이러한 점을 활용하여 연산 속도를 크게 향상할 수 있다.   
- 벡터화에 대한 자세한 (국문) 설명은 [여기](https://datascienceschool.net/01%20python/03.03%20%EB%B0%B0%EC%97%B4%EC%9D%98%20%EC%97%B0%EC%82%B0.html)에서, (영문) 설명은 [여기](https://www.pythonlikeyoumeanit.com/Module3_IntroducingNumpy/VectorizedOperations.html)에서 읽을 수 있다. 
- 넘파이에서 대부분의 연산은 벡터화되어 처리된다는 점을 기억하라.  
  따라서 어떤 작업이든 **배열 수준에서 처리**하려고 노력하라.  
  원소 수준에서 반복 논리로 처리하려는 접근 방식은 넘파이의 벡터화 장점을 포기하게 되는 것이며,  
  지양해야 한다.

In [166]:
# 이런 식으로 코드를 작성하지 마라!
array = np.arange(5)
for i, element in enumerate(array):  # 파이썬 리스트처럼 직접 반복 처리되지 않음
    array[i] = element ** 2

array

array([ 0,  1,  4,  9, 16])

In [167]:
# 이런 식으로 코드를 작성해야 벡터화 장점을 누릴 수 있다!
array = np.arange(5)
array **= 2 

array

array([ 0,  1,  4,  9, 16])

- 두 처리 방식의 코드 수행 시간을 비교 측정해보자.

In [168]:
# 반복 방식
array = np.array(range(5))
time_loop = %timeit -q -o -r 3 for i, element in enumerate(array): array[i] = element ** 2

# 벡터화 방식
array = np.array(range(5))
time_vect = %timeit -q -o -r 3 array ** 2
print(f"벡터화 방식이 반복 방식보다 {time_loop.average / time_vect.average:.2f}배 빠르다.")


벡터화 방식이 반복 방식보다 4.06배 빠르다.


- 벡터화 공부를 끝으로 넘파이 공부를 마친다.  
- 다음 장에서는 **판다스** 라이브러리 공부를 통하여  
  데이터 분석의 세상으로 한 걸음 더 들어가 보자. 