# 1장 넘파이


## 연습 문제

### 1.

넘파이를 `np`라는 별칭으로 수입하라. 

In [26]:
# 여기에 답안을 작성하라.


### 2.

다음과 같은 배열을 작성하고 결과를 출력하라:

1. 5개 `0`(zero)으로 구성된 배열을 생성하라.  
2. 10개 `1`(one)로 구성된 배열을 생성하라.  
3. 5개 `3.14`로 구성된 배열을 생성하라. 
4. 1에서 20까지의 정수로 구성된 배열을 생서하라. 
5. 자료형(dtype)이 `int`인 `1`로 구성된 5 x 5 행렬을 구성하라.  

In [27]:
# 여기에 답안을 작성하라.


[0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[3.141 3.141 3.141 3.141 3.141]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


### 3.

넘파이를 활용하여 다음 작업을 수행하라:
1. 표준정규분포를 따르는 난수로 채워진, 3 x 3 x 3 구조를 가지는 3차원 배열을 생성하라. (힌트: `np.random.randn()`)
2. 방금 생성한 배열을 모양이 (27,)인 행렬로 재구성하라. 

배열 내부 값은 난수이므로 아래와 다를 수 있다. 

In [28]:
# 여기에 배열 생성 답안을 작성하라.


array([[[-2.42667924, -0.42891263,  1.26593626],
        [-0.8667404 , -0.67888615, -0.09470897],
        [ 1.49138963, -0.638902  , -0.44398196]],

       [[-0.43435128,  2.20593008,  2.18678609],
        [ 1.0040539 ,  0.3861864 ,  0.73736858],
        [ 1.49073203, -0.93583387,  1.17582904]],

       [[-1.25388067, -0.6377515 ,  0.9071052 ],
        [-1.4286807 , -0.14006872, -0.8617549 ],
        [-0.25561937, -2.79858911, -1.7715331 ]]])

In [29]:
# 여기에 배열 재구성 답안을 작성하라.


array([-2.42667924, -0.42891263,  1.26593626, -0.8667404 , -0.67888615,
       -0.09470897,  1.49138963, -0.638902  , -0.44398196, -0.43435128,
        2.20593008,  2.18678609,  1.0040539 ,  0.3861864 ,  0.73736858,
        1.49073203, -0.93583387,  1.17582904, -1.25388067, -0.6377515 ,
        0.9071052 , -1.4286807 , -0.14006872, -0.8617549 , -0.25561937,
       -2.79858911, -1.7715331 ])

### 4.

(양 끝 점을 포함하는) [1, 10] 닫힌 구간(closed interval)에서,  
균등한 간격으로 나누어진 20개 값으로 구성된 배열을 생성하라.    

In [30]:
# 여기에 답안을 작성하라.


array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])

### 5.

아래에 5 x 5 모양인 배열을 정의해 두었다.  
인덱싱을 활용하여 아래 결과와 같이 출력하는 코드를 제시하라. 

In [31]:
a = np.arange(1, 26).reshape(5, -1)

```python
20
```

In [32]:
# 여기에 직전 출력과 같은 결과를 출력하는 답안을 작성하라.


20

```python
array([[ 9, 10],
       [14, 15],
       [19, 20],
       [24, 25]])
```

In [33]:
# 여기에 직전 출력과 같은 결과를 출력하는 답안을 작성하라.


array([[ 9, 10],
       [14, 15],
       [19, 20],
       [24, 25]])

```python
array([ 6,  7,  8,  9, 10])
```

In [34]:
# 여기에 직전 출력과 같은 결과를 출력하는 답안을 작성하라.

a[1]  # 또는 a[1,:]

array([ 6,  7,  8,  9, 10])

```python
array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])
```

In [35]:
# 여기에 직전 출력과 같은 결과를 출력하는 답안을 작성하라.


array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

```python
array([[ 8,  9],
       [13, 14]])
```

In [36]:
# 여기에 직전 출력과 같은 결과를 출력하는 답안을 작성하라.


array([[ 8,  9],
       [13, 14]])

### 6.

앞서 5번 문제에서 정의한 배열 `a`에 저장된 모든 값의 합계를 계산하라. 

In [37]:
# 여기에 답안을 작성하라.


325

### 7.

앞서 5번 문제에서 정의한 배열 `a`에 저장된 모든 값에 대하여 행별 합계를 계산하라. 


In [38]:
# 여기에 답안을 작성하라.


array([ 15,  40,  65,  90, 115])

### 8.

앞서 5번 문제에서 정의한 배열 `a`에 대하여, 배열 `a`의 평균치보다 큰 값을 모두 추출하라.

In [39]:
# 여기에 답안을 작성하라.


array([14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25])

### 9.

아래에서 정의한 배열 `b`에서 최소값의 위치를 출력하라. 

In [40]:
np.random.seed(123)
b = np.random.randn(10)
b

array([-1.0856306 ,  0.99734545,  0.2829785 , -1.50629471, -0.57860025,
        1.65143654, -2.42667924, -0.42891263,  1.26593626, -0.8667404 ])

In [41]:
# 여기에 답안을 작성하라.


6

### 10.

아래와 같은 2차원 배열 `c`에서 최대값의 위치를 출력하라. 
  
(힌트: 이 문제를 해결하는 방법이 다양하게 존재한다.  
스택오버플로우 사이트(stackoverflow.com)를 검색하면 이 문제에 대한 최적 해법을 쉽게 찾을 수 있다.  
예를 들어서, [기사](https://stackoverflow.com/questions/3584243/get-the-position-of-the-biggest-item-in-a-multi-dimensional-numpy-array)를 확인하라.)

In [42]:
np.random.seed(123)
c = np.random.randn(3, 2)
c

array([[-1.0856306 ,  0.99734545],
       [ 0.2829785 , -1.50629471],
       [-0.57860025,  1.65143654]])

In [43]:
# 여기에 답안을 작성하라.


  위치: (2, 1)
최대값: 1.65
